export const DATABASE_FIELDS = [
  { name: "stockId", label: "Stock #", required: true },
  { name: "carat", label: "Carat", required: true },
  { name: "price", label: "Price", required: false }, // Price is now optional
  { name: "availability", label: "Availability", required: false },
  { name: "shape", label: "Shape", required: false },
  { name: "color", label: "Color", required: false },
  { name: "clarity", label: "Clarity", required: false },
  { name: "cut", label: "Cut", required: false },
  { name: "polish", label: "Polish", required: false },
  { name: "symmetry", label: "Symmetry", required: false },
  { name: "lab", label: "Lab", required: false },
  { name: "reportNumber", label: "Report #", required: false },
  { name: "length", label: "Length", required: false },
  { name: "width", label: "Width", required: false },
  { name: "height", label: "Height", required: false },
  { name: "videoLink", label: "Video Link", required: false },
  { name: "imageLink", label: "Image Link", required: false },
  { name: "certificateLink", label: "Certificate Link", required: false },
  { name: "depthPercent", label: "Depth %", required: false },
  { name: "tablePercent", label: "Table %", required: false },
  { name: "pricePerCarat", label: "Price Per Carat", required: false },
  {
    name: "fluorescenceIntensity",
    label: "Fluorescence Intensity",
    required: false,
  },
  { name: "fluorescenceColor", label: "Fluorescence Color", required: false },
  { name: "girdleThin", label: "Girdle Thin", required: false },
  { name: "girdleThick", label: "Girdle Thick", required: false },
  { name: "girdlePercent", label: "Girdle %", required: false },
  { name: "girdleCondition", label: "Girdle Condition", required: false },
  { name: "culetSize", label: "Culet Size", required: false },
  { name: "culetCondition", label: "Culet Condition", required: false },
  { name: "crownHeight", label: "Crown Height", required: false },
  { name: "crownAngle", label: "Crown Angle", required: false },
  { name: "pavilionDepth", label: "Pavilion Depth", required: false },
  { name: "pavilionAngle", label: "Pavilion Angle", required: false },
  { name: "inscription", label: "Inscription", required: false },
  { name: "certificateComment", label: "Certificate Comment", required: false },
  { name: "keyToSymbols", label: "Key To Symbols", required: false },
  { name: "eyeClean", label: "Eye Clean", required: false },
  { name: "milky", label: "Milky", required: false },
  { name: "treatment", label: "Treatment", required: false },
  { name: "location", label: "Location", required: false },
  { name: "city", label: "City", required: false },
  { name: "state", label: "State", required: false },
  {
    name: "countryOfPolishing",
    label: "Country of Polishing",
    required: false,
  },
  { name: "type", label: "Type", required: false },
];
